### ISSUE TITLE
Actualización y pantalla en blanco

### ISSUE THREAD

**Issue by Gomez-Israel** [erikkaashoek/NanoVNA#103]
Hola a todos, tuve un problema al actualizar mi tiny Sa por medio de STM32.
Después de cargar la ultima versión mi pantalla quedo en blanco.
Trate el método Vcc Boot0 y sigue igual.
Me percate que en el software marca todas las direcciones como "sector 0046 does not exist"
Existe alguna forma de poder instalarle toda la información desde cero?
Espero puedan ayudarme
![1b17a2a8-e317-4b70-b96b-a3770b35d3c1](https://github.com/erikkaashoek/tinySA/assets/88797079/17136394-302f-4f6b-bd55-c95fa798eb53)
![cba5672c-5f4d-45cb-a70d-9606fa0eec5c](https://github.com/erikkaashoek/tinySA/assets/88797079/9904eb2e-45bc-4173-a203-b9e266447459)

**Comment by erikkaashoek** [comment]
Do not use STMCube programmer 2.16, only use version 2.15
