### ISSUE TITLE
Trigger not working?

### ISSUE THREAD

**Issue by mrbazza** [erikkaashoek/NanoVNA#104]
TinySAUltra 1.4-151
Source signal is button remote @ 2422MHz + 2432MHz.  … running TinySAUltras in zero span mode 
I can observe these signals in zero span mode with auto trigger and display shows frequency bursts of up to -60dbm and noise floor around -100dbm as expected. scan time set to 1s.
However i dont seem to be able to trigger in normal or single modes with trigger level set to say -90dbm. I have tried different trigger levels and settings for pre/mid/post up/down and unable to get a definite trigger when remote buttons are pressed. Trigger remains armed but occasionally fires with unpredictable display position on x axis i.e. not at trigger position. Revert to auto trigger and display shows (without trigger sync of course)
Trigger does not trigger the way im expecting but maybe i have this wrong :-)

**Comment by erikkaashoek** [comment]
Try to disable spur reduction and test if this improves the triggering,

**Comment by mrbazza** [comment]
Thanks Erik, that does appear to have resolved the triggering issue I was having. Triggering now works as I had expected and Pre/Mid /Post all align spot on now.CheersBarry IrelandOn 22 Jun 2024, at 5:20 AM, erikkaashoek ***@***.***> wrote:﻿
Try to disable spur reduction and test if this improves the triggering,
