### ISSUE TITLE
Not starting after Firmware Update

### ISSUE THREAD

**Issue by Vincenteich** [erikkaashoek/NanoVNA#105]
Hi,

I just made the Firmware Update using SMT32 using the .bin file and did exactly as described in the directions. After restartig nothing happened. The screen jsut stays Black. What went wrong and does anyone know how ti fix it?

best regards in advance!

This is the log from the SMT 32:

  15:43:13 : Read File: C:\Users\veich\Downloads\tinySA4_v1.4-156-g4eb315d.bin
  15:43:13 : Number of segments: 1
  15:43:13 : segment[0]: address= 0x0, size= 0x2C134
  15:43:18 : Memory Programming ...
  15:43:18 : Opening and parsing file: tinySA4_v1.4-156-g4eb315d.bin
  15:43:18 :   File          : tinySA4_v1.4-156-g4eb315d.bin
  15:43:18 :   Size          : 176.30 KB 
  15:43:18 :   Address       : 0x08000000 
  15:43:18 : Erasing memory corresponding to segment 0:
  15:43:18 : Erasing internal memory sectors [0 88]
  15:43:18 : sector 0000 does not exist
  15:43:18 : sector 0001 does not exist
  15:43:18 : sector 0002 does not exist
  15:43:18 : sector 0003 does not exist
  15:43:18 : sector 0004 does not exist
  15:43:18 : sector 0005 does not exist
  15:43:18 : sector 0006 does not exist
  15:43:18 : sector 0007 does not exist
  15:43:18 : sector 0008 does not exist
  15:43:18 : sector 0009 does not exist
  15:43:18 : sector 0010 does not exist
  15:43:18 : sector 0011 does not exist
  15:43:18 : sector 0012 does not exist
  15:43:18 : sector 0013 does not exist
  15:43:18 : sector 0014 does not exist
  15:43:18 : sector 0015 does not exist
  15:43:18 : sector 0016 does not exist
  15:43:18 : sector 0017 does not exist
  15:43:18 : sector 0018 does not exist
  15:43:18 : sector 0019 does not exist
  15:43:18 : sector 0020 does not exist
  15:43:18 : sector 0021 does not exist
  15:43:18 : sector 0022 does not exist
  15:43:18 : sector 0023 does not exist
  15:43:18 : sector 0024 does not exist
  15:43:18 : sector 0025 does not exist
  15:43:18 : sector 0026 does not exist
  15:43:18 : sector 0027 does not exist
  15:43:18 : sector 0028 does not exist
  15:43:18 : sector 0029 does not exist
  15:43:18 : sector 0030 does not exist
  15:43:18 : sector 0031 does not exist
  15:43:18 : sector 0032 does not exist
  15:43:18 : sector 0033 does not exist
  15:43:18 : sector 0034 does not exist
  15:43:18 : sector 0035 does not exist
  15:43:18 : sector 0036 does not exist
  15:43:18 : sector 0037 does not exist
  15:43:18 : sector 0038 does not exist
  15:43:18 : sector 0039 does not exist
  15:43:18 : sector 0040 does not exist
  15:43:18 : sector 0041 does not exist
  15:43:18 : sector 0042 does not exist
  15:43:18 : sector 0043 does not exist
  15:43:18 : sector 0044 does not exist
  15:43:18 : sector 0045 does not exist
  15:43:18 : sector 0046 does not exist
  15:43:18 : sector 0047 does not exist
  15:43:18 : sector 0048 does not exist
  15:43:18 : sector 0049 does not exist
  15:43:18 : sector 0050 does not exist
  15:43:18 : sector 0051 does not exist
  15:43:18 : sector 0052 does not exist
  15:43:18 : sector 0053 does not exist
  15:43:18 : sector 0054 does not exist
  15:43:18 : sector 0055 does not exist
  15:43:18 : sector 0056 does not exist
  15:43:18 : sector 0057 does not exist
  15:43:18 : sector 0058 does not exist
  15:43:18 : sector 0059 does not exist
  15:43:18 : sector 0060 does not exist
  15:43:18 : sector 0061 does not exist
  15:43:18 : sector 0062 does not exist
  15:43:18 : sector 0063 does not exist
  15:43:18 : sector 0064 does not exist
  15:43:18 : sector 0065 does not exist
  15:43:18 : sector 0066 does not exist
  15:43:18 : sector 0067 does not exist
  15:43:18 : sector 0068 does not exist
  15:43:18 : sector 0069 does not exist
  15:43:18 : sector 0070 does not exist
  15:43:18 : sector 0071 does not exist
  15:43:18 : sector 0072 does not exist
  15:43:18 : sector 0073 does not exist
  15:43:18 : sector 0074 does not exist
  15:43:18 : sector 0075 does not exist
  15:43:18 : sector 0076 does not exist
  15:43:18 : sector 0077 does not exist
  15:43:18 : sector 0078 does not exist
  15:43:18 : sector 0079 does not exist
  15:43:18 : sector 0080 does not exist
  15:43:18 : sector 0081 does not exist
  15:43:18 : sector 0082 does not exist
  15:43:18 : sector 0083 does not exist
  15:43:18 : sector 0084 does not exist
  15:43:18 : sector 0085 does not exist
  15:43:18 : sector 0086 does not exist
  15:43:18 : sector 0087 does not exist
  15:43:18 : sector 0088 does not exist
  15:43:18 : Download in Progress:
  15:43:22 : File download complete
  15:43:22 : Time elapsed during download operation: 00:00:04.121
  15:43:29 : Disconnected from device.

**Comment by Vincenteich** [comment]
Solved, just use the Windows comand file DfU_Load_Bin.bat

**Comment by yannciv** [comment]
Hello, I have the same problem and i can't find drivers on windows. How do you execute this windows command ? Thank you

**Comment by Vincenteich** [comment]
> Hello, I have the same problem and i can't find drivers on windows. How do you execute this windows command ? Thank you

**Updating the firmware using a bin file and dfu-util(Windows, Linux and Mac)
This is an alternative to using STM32CubeProgrammer

Get the tinySA_version_number.bin file from http://athome.kaashoek.com/tinySA/DFU/ or for the tinySA Ultra from http://athome.kaashoek.com/tinySA4/DFU/ and also download from there the files with names starting with DFU

Rename the downloaded file to tinySA.bin

Connect the tinySA with USB and activate the DFU mode:

tinySA: switch the tinySA on and enter [DFU](https://tinysa.org/wiki/pmwiki.php?n=Main.CONFIG) mode.
tinySA Ultra: press the jog button before switching on the tinySA Ultra. Switch on and the screen should stay black.
Download dfu-util from http://dfu-util.sourceforge.net/releases/ and check that you can execute it.

For windows, open a command window and go to the folder with the downloaded files and run DFU_LOAD_BIN.bat. The tinySA should now be updating with the tinySA.bin file using dfu-util-static.exe**

You can open a Command Window by Typing cmd in your windows search. 

or Windows  Key+R, then type in cmd

I think you can also Just execute DFU_LOAD_BIN.bat. Windows will ask if you really wanna open it. Click yes ind it should work, if you got the other files.

**Comment by erikkaashoek** [comment]
STM32Cube programmer 2.16 has a bug
Only use 2.15 or earlier
