### ISSUE TITLE
Waterfall image is cleared when closing the right menu

### ISSUE THREAD

**Issue by aagorchakov** [erikkaashoek/NanoVNA#108]
Hello, I noticed a small bug, Waterfall image is cleared every time when closing the right menu.
It can especially important when enabling Listen mode in the menu. In this case Waterfall image is lost and it becomes more difficult to find the necessary frequencies.

Expected Behavior: Waterfall image is not affected when closing the right menu.
Actual Behavior: Waterfall area area turns black, Waterfall image is cleared.

Running the latest TinySA Ultra version 1.4-165.

**Comment by erikkaashoek** [comment]
This is unavoidable as there is no backup image of the waterfall.
