### ISSUE TITLE
firmware uploading troubles 

### ISSUE THREAD

**Issue by privategore** [erikkaashoek/NanoVNA#110]
Hello here! Im not English native, so my apologies about mistakes. Trying to upgrade firmware for Tiny SA Ultra. Try USB connection and UART connection also. In result my laptop(trying with a 3 different machines) recognize the device(tiny in DFU at the moment), BUT when we go to the flashing point. msg from the system is something like Device is not connected. 
Any issues?
Thanks and Best!

**Comment by erikkaashoek** [comment]
Please go to wiki and follow one of the indicated procedures
If this fails, go to the tinySA support group for more help

**Comment by erikkaashoek** [comment]
Further support in tinySA support group
