### ISSUE TITLE
Arquivo .CSV

### ISSUE THREAD

**Issue by alexraffel** [erikkaashoek/NanoVNA#19]
Boa tarde, me chamo Alex comprei um tinySA no caso quero gerer CSN para WWb6 da Shure, porem ele não esta abrindo no wwB6 shure por conta do padrao Exemplo 560.000,-61.00 precisava sair assim meu email alexraffel@me.com

**Comment by alexraffel** [comment]
Tem como na hora que gerar no TinySa CSV saia neste Padrão 560.000,-61.00 ?

**Comment by erikkaashoek** [comment]
No hablo espagnol

**Comment by erikkaashoek** [comment]
Please ask general support questions here: https://groups.io/g/tinysa/messages
