### ISSUE TITLE
tinySA Lo input doesnt work. Selftest stopped at 3 vith message Test 3 signal level fail

### ISSUE THREAD

**Issue by ponkka** [erikkaashoek/NanoVNA#20]
Lo input doesnt work at all. Selftest stopped at test3. Level cal. says Signal level to low. I´we changed cables, it doesn´t work. 
It started with suggestions to change cable between Lo and HI inputs but test doesn´t pass successfully. tinySA bought from ELESHOP.EU

**Comment by erikkaashoek** [comment]
Please ask general support questions here: https://groups.io/g/tinysa/messages
