### ISSUE TITLE
Tag mismatch -> built versions are still on v1.2-nnn

### ISSUE THREAD

**Issue by Ho-Ro** [erikkaashoek/NanoVNA#35]
Hello Erik,
when I build from your cloned repo I still get Versions like tinySA_**v1.2**-nnn-gxxx... because tag `v1.2` is newer than `v1.3`, as seen on the GitHub [tags](https://github.com/erikkaashoek/tinySA/tags) page (see below).
According to your download page `2af1845` is `v1.3-3`, so `v1.3` should be `12a96bb` from _Mon Mar 29 08:58:52 2021 +0200_ but it is `232494b` from _26 Feb 2021_  while `v1.2` is two days later from _28 Feb 2021_.

[tinySA_v1.3-3-g2af1845.bin](http://athome.kaashoek.com/tinySA/DFU/old/tinySA_v1.3-3-g2af1845.bin) and [tinySA4_v1.3-3-g2af1845.bin](http://athome.kaashoek.com/tinySA4/DFU/old/tinySA4_v1.3-3-g2af1845.bin)

git log shows this:
```
commit 2af18458bc248b9c1ef683caf79cd0cba8c89465
Author: erikkaashoek <erik@kaashoek.com>
Date:   Tue Mar 30 15:02:08 2021 +0200

    More spur improvements

commit a42a1f50216a3df31a3e102204686f6f8f07916d
Author: erikkaashoek <erik@kaashoek.com>
Date:   Tue Mar 30 13:49:58 2021 +0200

    Added NEAR SPUR

commit 02f06319d8b93cda32f52a6afac9420fccf5f8d1
Author: erikkaashoek <erik@kaashoek.com>
Date:   Mon Mar 29 17:45:46 2021 +0200

    Correction updates

commit 12a96bba04f2bae690076569a21f214e4a4ace88
Author: erikkaashoek <erik@kaashoek.com>
Date:   Mon Mar 29 08:58:52 2021 +0200

    Repaired test status and marker colors

``` 

GitHub tags page:

![image](https://user-images.githubusercontent.com/12542359/200197141-d17871fd-f8a0-4d64-b744-62c39b3f6496.png)

**Comment by Ho-Ro** [comment]
@erikkaashoek: If you do a fresh clone of your V3.4 branch, what does `git describe --tags` announce?
Do I miss some initialisation to get the correct versioning like **v1.3**-nnn-gxxxxxxx?
I hacked it for me by deleting the old v1.3 tag and defining a new annotated tag `v1.3` at `12a96bb`.

This is what I get from a fresh clone:

``` shell
$ git clone https://github.com/erikkaashoek/tinySA.git tinySA_tag_test
Cloning into 'tinySA_tag_test'...
remote: Enumerating objects: 8895, done.
remote: Counting objects: 100% (2530/2530), done.
remote: Compressing objects: 100% (692/692), done.
remote: Total 8895 (delta 1913), reused 2427 (delta 1826), pack-reused 6365
Receiving objects: 100% (8895/8895), 4.88 MiB | 8.36 MiB/s, done.
Resolving deltas: 100% (6659/6659), done.

$ cd tinySA_tag_test/

$ git submodule update --init --recursive 
Submodule 'ChibiOS' (https://github.com/edy555/ChibiOS.git) registered for path 'ChibiOS'
Cloning into '/home/horo/projects/tinySA/tinySA_tag_test/ChibiOS'...
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 86 (delta 59), reused 59 (delta 59), pack-reused 24
Unpacking objects: 100% (86/86), 234.13 KiB | 1.73 MiB/s, done.
From https://github.com/edy555/ChibiOS
 * branch                ade76dea89cd093650552328e881252a06486094 -> FETCH_HEAD
Submodule path 'ChibiOS': checked out 'ade76dea89cd093650552328e881252a06486094'

$ git checkout V4.3 
Branch 'V4.3' set up to track remote branch 'V4.3' from 'origin'.
Switched to a new branch 'V4.3'

$ git describe 
v1.2-595-g6464f77

$ git describe --tags
v1.2-595-g6464f77

$ git fetch --tags

$ git describe 
v1.2-595-g6464f77

$ git describe --tags
v1.2-595-g6464f77
```

**Comment by erikkaashoek** [comment]
I have no clue, git is a bit too complex for me.

**Comment by Ho-Ro** [comment]
See also this [groups.io discussion](https://groups.io/g/tinysa/topic/95657859#8619).

**Comment by Ho-Ro** [comment]
So that the link is not lost: Here's the [V4.3 renaming how-to](https://groups.io/g/tinysa/files/Firmware_Programming/Rename_tinySA_V4.3_to_main.pdf).

**Comment by Ho-Ro** [comment]
Back to sync with v1.4 - close
