### ISSUE TITLE
TinySA Noise Figure

### ISSUE THREAD

**Issue by s5pecAn** [erikkaashoek/NanoVNA#41]
I compute the Noise Figure of the TinySA on HIGH in as follows:
- No Input
- Frequency = 488, 506, 542 & 569 MHz
- Span = 6 MHz
- TRACE/CALC/AVER16
- MARKER/SEARCH MARKER/FREQUENCY
- Displayed Average Noise Floor (DANF) = -117.2 dBm/42kHz
- Ambient Temperature = 296K
================================
  10*log(kT*B*Nf) = DANF + 2.51 dB
  10*log(kT) = -173.89 dBm/Hz, 10*log(B) = 46.23 dBHz, 2.51 dB corrects for averaging of logarithmic values
- Solving for Nf,
  Nf = -117.2 + 2.51 - (-173.89) - 46.23 = 12.97 dB

  Do you agree?
  Does the 2.51 dB apply?

**Comment by erikkaashoek** [comment]
Why do you want to add 2.51dB?
Why not use the noise markers as this will use the ENBW of the used resolution filter
And why not use the MEASURE/MORE/NOISE FIGURE?

**Comment by s5pecAn** [comment]
Hi Erik,Many thanks for your response.
Your questions followed by my replies below. Why do you want to add 2.51dB?
Averaging of logarithmic values is not the same as the log of the average. The average value of noise, a Gaussian variable G(t) with mu=0 and sigma=1, is the Expectation[20*log(|G(t)|) = -2.51 dB. I assume the detector in the TinySA is a sample detector for which this correction applies. If the detector is an rms detector, this correction would not apply. Why not use the noise markers as this will use the ENBW of the used resolution filter
I used this handy option, but it does not answer the question of the detector type. And why not use the MEASURE/MORE/NOISE FIGURE?
My TinySA is H/W: V0.3.1_EL, S/N: SA-22061510, purchased from R&L Electronics, 9/25/2022; it does not have a MEASURE/MORE/NOISE FIGURE option. Perhaps we can close this question with the detector type, (a) sample, (b) rms or (c) average detector. Thank youSincerelySteve Dutka, P.E.

---------- Original Message ----------

**Comment by erikkaashoek** [comment]
The noise markers are compensating for any averaging effect in the primary level measurement.
Any further averaging is done in the linear power domain.

**Comment by s5pecAn** [comment]
How do the noise markers compensate for any averaging effect in the primary level measurement? Please elaborate.What is "primary level measurement"?What is meant by "further averaging"? Do the noise markers display the rms value?

---------- Original Message ----------

**Comment by erikkaashoek** [comment]
The level measured by noise markers has been calibrated using a calibrated noise source and by comparing them to the noise level measurements from another calibrated spectrum analyzer for each RBW.

**Comment by s5pecAn** [comment]
I measured the following today:
- No input
- Mode: HIGH in
- Frequency: 488 MHz
- Span: 2 MHz
- MARKER/SEARCH MARKER/ENTER FREQUENCY (488 MHz)
- TRACE/CALC/AVER16
=================================
-- Read-out at top of screen: -118.7 dBm/14kHz (the trace itself)
- MARKER/MODIFY MARKER/NOISE (checked)
-- Read-out at top of screen: -160.2 dBm/Hz
=================================
The read-out is -118.7 - 10*log(14E03) = -160.2 dBm/Hz.
The trace is at the same level, approx -119 dBm in 14 kHz.
So there is no 2.51 dB correction added to the noise marker. Am I missing something here? You said the TinySA corrects for log averaging in Issue #31. Does my TinySA have the 2.51 dB correction built-in?
If so, how should I configure it to get the correction?

---------- Original Message ----------

**Comment by erikkaashoek** [comment]
Trace/calc/aver16 is linear power averaging, not averaging of the dB.
The shape of the resolution filters in the tinySA is almost rectangular, not gaussian.
Why do you want to correct?

**Comment by s5pecAn** [comment]
I FINALLY get it!These very important words made for easy understanding: "aver16 is linear power averaging, not averaging of the dB."These words would be very helpful in your wiki.The displayed level is the log of the linear averages. Question answered. No correction needed.
---------- Original Message ----------
