### ISSUE TITLE
Tiny SA Ultra - sweep time in generator mode

### ISSUE THREAD

**Issue by peermanent** [erikkaashoek/NanoVNA#53]
I would like to use the Ultra as a signal generator to see the filter curve of a 10,7 MHz filter at an oscilloscope. By setting the sweep time to 50 msec it seems that the sweep time isn´t 50 msec but approx 500 msec. Using the TinySA all works fine

Following setup:

Ultra RF output to the 10,7 MHz filter input
Ultra Cal output to oscilloscope ext. trigger input
Filter output to oscillosocpe y-input

Ultra setting:
frequency 10,7MHz
sweep span 1 MHz
sweep time 50 msec
sweep points 201

**Comment by peermanent** [comment]
![Filter curve when using Tiny SA](https://user-images.githubusercontent.com/121577097/209865445-81214d5b-76bd-4461-b279-92de13085c04.jpg)

**Comment by peermanent** [comment]
the picture shows a 10,7 MHz filter curve when using the TinySA with a sweep time of 50 msec

**Comment by erikkaashoek** [comment]
The minimum sweep time of the Ultra is 10 times larger compared to the Classic.
