### ISSUE TITLE
Large spectra amplitude near frequencies close to 0.

### ISSUE THREAD

**Issue by good-point-lab** [erikkaashoek/NanoVNA#54]
I am not sure this is an issue and I can not find an answer on the net - on my new TinySA Ultra (4.5.1 tinySA4_v1.3-506-g8291e1e) after self-test and calibration I observe a spike (a thin yellow strip) along amplitude axis for frequency very close to 0.  The strip is present no matter what frequency range is selected.  I have not tried less than 100KHz.  If TinySA blocks DC, what could be the cause of the spectra close to 0?  A number of available pictures of the device show similar behavior.

![example](https://user-images.githubusercontent.com/4474158/210683054-7cf2b6ed-6a0b-45f6-b889-c3c629a12350.jpeg)

**Comment by Ho-Ro** [comment]
This is the normal behaviour due to the technical realisation of a SA.
