### ISSUE TITLE
tinySA3: BIG NUMBER graph is displayed in the size of big WATERFALL

### ISSUE THREAD

**Issue by Ho-Ro** [erikkaashoek/NanoVNA#61]
Regression with d758676

https://groups.io/g/tinysa/message/10620

![image](https://user-images.githubusercontent.com/12542359/226166489-0b4ecd13-55ee-4993-8e6d-1bcb29f97e8b.png)

**Comment by erikkaashoek** [comment]
Solved in 1.4075
