### ISSUE TITLE
Steps in spectrum at low freq.

### ISSUE THREAD

**Issue by Rooby69** [erikkaashoek/NanoVNA#81]
Hello

when I set start freq 100kHz and stop to 1.5MHz, RBW to auto
I get the following picture:
![TEST](https://github.com/erikkaashoek/tinySA/assets/41417582/573c611f-d82d-4c25-9387-ad791bed93cd)
Are this steps in the spectrum normal?

Thanks
Stefan

**Comment by Ho-Ro** [comment]
Yes, check Erik's videos on youtube about this behavior.
