### ISSUE TITLE
Convert TinySA csvs to WWB

### ISSUE THREAD

**Issue by peterfealey** [erikkaashoek/NanoVNA#82]
Hi! I just wanted to pop by to say I am in the Signal to Noise Discord and a couple of folks were trying to use various tools to convert TinySA .csvs to Shure WWB compatible CSVs. 

I've made a little tool, free of charge, hosted at peterfealey.co.uk if it's of use to anyone in a pinch.

**Comment by erikkaashoek** [comment]
Implemented in latest FW
