### ISSUE TITLE
SAVE CAPTURE erases the waterfall just before saving the image

### ISSUE THREAD

**Issue by Lathe26** [erikkaashoek/NanoVNA#92]
When the waterfall is shown on the screen and then STORAGE -> SAVE CAPTURE is a selected, the waterfall portion of the screen isn't saved to the file.

**Comment by erikkaashoek** [comment]
The waterfall is only stored in display memory so any action on the screen that draws a menu or keybad destroys the waterfall. This can not be solved.
To save the screen with waterfall, tap the SD card icon

**Comment by Lathe26** [comment]
Thanks for the suggestion.

I'll add that for anyone else who reads this in the future that Auto Name needs to be enabled _and_ no menu can active on the screen.  This bypasses the keypad for typing in a file name when the user taps the SD card icon.

**Comment by repentsinner** [comment]
Thanks for the workaround @erikkaashoek, unfortunate that it's required. In general the waterfall is one of the more useful features of this device, would be great if it was a little more robust (e.g., double buffered w/r/t the UI).

**Comment by erikkaashoek** [comment]
Many things would be nice but are impossible with the current HW
